---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - autorecon
      - curl # check Requirement for Autorecon
      - dnsrecon # check Requirement for Autorecon
      - enum4linux # check Requirement for Autorecon
      - evil-winrm
      - exiftool
      - fcrackzip
      - feroxbuster # check Requirement for Autorecon
      - ffuf
      - flameshot
      - fzf
      - gobuster # check Requirement for Autorecon
      - golang
      - impacket-scripts # check Requirement for Autorecon
      - inkscape
      - mingw-w64
      - nbtscan # check Requirement for Autorecon
      - ncat
      - nikto # check Requirement for Autorecon
      - nmap # check Requirement for Autorecon
      - onesixtyone # check Requirement for Autorecon
      - oscanner # check Requirement for Autorecon
      - pipx
      - redis-tools # check Requirement for Autorecon
      - rlwrap
      - seclists
      - smbclient # check Requirement for Autorecon
      - smbmap # check Requirement for Autorecon
      - snmp # check Requirement for Autorecon
      - sslscan # check Requirement for Autorecon
      - sipvicious # check Requirement for Autorecon
      - tmux
      - tnscmd10g # check Requirement for Autorecon
      - unzip
      - whatweb # check Requirement for Autorecon
      - wkhtmltopdf # check Requirement for Autorecon
    state: latest
  become: true
  become_method: sudo
