---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/tools-installation"
    - role: "roles/browser-customization"
    - role: "roles/system-configuration"
    - role: "roles/tmux-configuration"
