---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/tools-installation"
    - role: "roles/browser-customization"
    - role: "roles/system-configuration"
    - role: "roles/tmux-configuration"
    - role: "roles/vscode-installation"
      users:
        - username: kali
          visual_studio_code_extensions:
            - patmood.rich-markdown-editor
            - donjayamanne.git-extension-pack
