---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copying Tmux Config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"
- name: "Installation of Tmux Plugin Manager"
  ansible.builtin.git:   
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"    
- name: "Installation of Tmux Plugins"
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins
