---
- name: Copying OLED Black wallpaper
  ansible.builtin.copy:
    src: "{{ role_path }}/files/blackoled.jpg"
    dest: "/usr/share/backgrounds/kali-16x9/blackoled.jpg"
  become: true
  become_user: root

- name: Change wallpaper to OLED Black
  community.general.xfconf:
    channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorVirtual1/workspace0/last-image"
    value_type: "string"
    value: "blackoled.jpg"

- name: Change Lock Screen by creating a symbolic link
  ansible.builtin.file:
    src: "/usr/share/backgrounds/kali-16x9/blackoled.jpg"
    dest: "/usr/share/desktop-base/kali-theme/login/background" 
    state: link
  become: true
  become_user: root
