---
- name: "Copying OLED Black wallpaper"
  copy:
    src: "{{ role_path }}/files/blackoled.jpg"
    dest: "/usr/share/backgrounds/kali-16x9/"

- name: Change wallpaper to OLED Black
  xfconf:
    channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorVirtual1/workspace0/last-image"
    value_type: "string"
    value: "blackoled.jpg"

- name: Change Lock Screen Wallpaper
  shell: ln -s /usr/share/backgrounds/kali-16x9/blackoled.jpg /usr/share/desktop-base/kali-theme/login/background
  become: true
  become_user: root