- name: somerepo |no apt key
    ansible.builtin.get_url:
      url: https://apt.fury.io/wez/gpg.key
      dest: /usr/share/keyrings/wezterm-fury.gpg
        
- name: somerepo | apt source
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
      state: present

- name: "Installing Wezterm"
  package:
    name:
      - wezterm
    state: latest
    update_cache: yes
  become: true
  become_method: sudo
  
