---
vars:
  wezterm-config: "{{ ansible_env.HOME }}/.config/wezterm/wezterm.lua"
  
- name: somerepo |no apt key
    ansible.builtin.get_url:
      url: https://apt.fury.io/wez/gpg.key
      dest: /usr/share/keyrings/wezterm-fury.gpg
        
- name: somerepo | apt source
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
      state: present

- name: "Installing Wezterm"
  package:
    name:
      - wezterm
    state: latest
    update_cache: yes
  become: true
  become_method: sudo

- name: "Make sure wezterm config dir exists"
  file:
    path: "{{ wezterm-config | dirname }}"
    state: directory

- name: "Install Ioveska Font:
  ansible.builtin.shell:
    cmd: wget -O fonts-iosevka.deb \
  https://sid.ethz.ch/debian/fonts-iosevka/fonts-iosevka_22.0.0%2Bds-1_all.deb \
  && sudo dpkg -i fonts-iosevka.deb \
  && rm fonts-iosevka.deb \
  && sudo fc-cache -fv
          
- name: "Copying wezterm conf"
  copy:
    src: "{{ role_path }}/files/wezterm.lua"
    dest: "{{ wezterm-config }}"
