---
- name: "Copying .zshrc config"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dotzshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: "Install interactive cheat sheet tool Navi"
  ansible.builtin.shell: |
    bash -c "bash <(curl -sL https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install)"

- name: "Add cheatsheets to Navi"
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.cargo/bin/navi repo add https://github.com/denisidoro/cheats
